package de.dfki.smartfactoryKL.ontology.impl;

import de.dfki.smartfactoryKL.ontology.Vocabulary;
import de.dfki.smartfactoryKL.ontology.WeighingModule;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;

import java.util.Collection;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultWeighingModule <br>
 * @version generated on Sat Mar 25 23:36:09 CET 2017 by Utkarsh
 */
public class DefaultWeighingModule extends WrappedIndividualImpl implements WeighingModule {

    public DefaultWeighingModule(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#getsDataFrom
     */

    public Collection<? extends WrappedIndividual> getGetsDataFrom() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_GETSDATAFROM,
                WrappedIndividualImpl.class);
    }

    public boolean hasGetsDataFrom() {
        return !getGetsDataFrom().isEmpty();
    }

    public void addGetsDataFrom(WrappedIndividual newGetsDataFrom) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_GETSDATAFROM,
                newGetsDataFrom);
    }

    public void removeGetsDataFrom(WrappedIndividual oldGetsDataFrom) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_GETSDATAFROM,
                oldGetsDataFrom);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#hasContainer
     */

    public Collection<? extends WrappedIndividual> getHasContainer() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_HASCONTAINER,
                WrappedIndividualImpl.class);
    }

    public boolean hasHasContainer() {
        return !getHasContainer().isEmpty();
    }

    public void addHasContainer(WrappedIndividual newHasContainer) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_HASCONTAINER,
                newHasContainer);
    }

    public void removeHasContainer(WrappedIndividual oldHasContainer) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_HASCONTAINER,
                oldHasContainer);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#isKeptOn
     */

    public Collection<? extends WrappedIndividual> getIsKeptOn() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_ISKEPTON,
                WrappedIndividualImpl.class);
    }

    public boolean hasIsKeptOn() {
        return !getIsKeptOn().isEmpty();
    }

    public void addIsKeptOn(WrappedIndividual newIsKeptOn) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_ISKEPTON,
                newIsKeptOn);
    }

    public void removeIsKeptOn(WrappedIndividual oldIsKeptOn) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_ISKEPTON,
                oldIsKeptOn);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#providesDataTo
     */

    public Collection<? extends WrappedIndividual> getProvidesDataTo() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_PROVIDESDATATO,
                WrappedIndividualImpl.class);
    }

    public boolean hasProvidesDataTo() {
        return !getProvidesDataTo().isEmpty();
    }

    public void addProvidesDataTo(WrappedIndividual newProvidesDataTo) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_PROVIDESDATATO,
                newProvidesDataTo);
    }

    public void removeProvidesDataTo(WrappedIndividual oldProvidesDataTo) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                Vocabulary.OBJECT_PROPERTY_PROVIDESDATATO,
                oldProvidesDataTo);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Precision_of_weighing_sensor
     */

    public Collection<? extends Object> getPrecision_of_weighing_sensor() {
        return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PRECISION_OF_WEIGHING_SENSOR, Object.class);
    }

    public boolean hasPrecision_of_weighing_sensor() {
        return !getPrecision_of_weighing_sensor().isEmpty();
    }

    public void addPrecision_of_weighing_sensor(Object newPrecision_of_weighing_sensor) {
        getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PRECISION_OF_WEIGHING_SENSOR, newPrecision_of_weighing_sensor);
    }

    public void removePrecision_of_weighing_sensor(Object oldPrecision_of_weighing_sensor) {
        getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PRECISION_OF_WEIGHING_SENSOR, oldPrecision_of_weighing_sensor);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Total_number_of_parts
     */

    public Collection<? extends Object> getTotal_number_of_parts() {
        return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTAL_NUMBER_OF_PARTS, Object.class);
    }

    public boolean hasTotal_number_of_parts() {
        return !getTotal_number_of_parts().isEmpty();
    }

    public void addTotal_number_of_parts(Object newTotal_number_of_parts) {
        getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTAL_NUMBER_OF_PARTS, newTotal_number_of_parts);
    }

    public void removeTotal_number_of_parts(Object oldTotal_number_of_parts) {
        getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTAL_NUMBER_OF_PARTS, oldTotal_number_of_parts);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Total_weight
     */

    public Collection<? extends Object> getTotal_weight() {
        return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTAL_WEIGHT, Object.class);
    }

    public boolean hasTotal_weight() {
        return !getTotal_weight().isEmpty();
    }

    public void addTotal_weight(Object newTotal_weight) {
        getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTAL_WEIGHT, newTotal_weight);
    }

    public void removeTotal_weight(Object oldTotal_weight) {
        getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOTAL_WEIGHT, oldTotal_weight);
    }


}
