package de.dfki.smartfactoryKL.ontology;


import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.*;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sat Mar 25 23:36:08 CET 2017 by Utkarsh
 */

public class Vocabulary {

    private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Container
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTAINER.<p>
     * 
     */
    public static final OWLClass CLASS_CONTAINER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Container"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#RFID
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RFID.<p>
     * 
     */
    public static final OWLClass CLASS_RFID = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#RFID"));

    /* ***************************************************
     * Class http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#WeighingModule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WEIGHINGMODULE.<p>
     * 
     */
    public static final OWLClass CLASS_WEIGHINGMODULE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#WeighingModule"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#getsDataFrom
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property GETSDATAFROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_GETSDATAFROM = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#getsDataFrom"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#hasContainer
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTAINER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTAINER = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#hasContainer"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#isKeptOn
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISKEPTON.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISKEPTON = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#isKeptOn"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#providesDataTo
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property PROVIDESDATATO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PROVIDESDATATO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#providesDataTo"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Breadth
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property BREADTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BREADTH = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Breadth"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Height
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property HEIGHT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HEIGHT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Height"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Inventory
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property INVENTORY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INVENTORY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Inventory"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Length
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property LENGTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LENGTH = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Length"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Part_description
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property PART_DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PART_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Part_description"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Precision_of_weighing_sensor
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property PRECISION_OF_WEIGHING_SENSOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PRECISION_OF_WEIGHING_SENSOR = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Precision_of_weighing_sensor"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Tolerance_of_weight
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOLERANCE_OF_WEIGHT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOLERANCE_OF_WEIGHT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Tolerance_of_weight"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Total_number_of_parts
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOTAL_NUMBER_OF_PARTS.<p>
     */
    public static final OWLDataProperty DATA_PROPERTY_TOTAL_NUMBER_OF_PARTS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Total_number_of_parts"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Total_weight
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOTAL_WEIGHT.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_TOTAL_WEIGHT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Total_weight"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Weight_of_box
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property WEIGHT_OF_BOX.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_WEIGHT_OF_BOX = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Weight_of_box"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Weight_per_piece
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property WEIGHT_PER_PIECE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_WEIGHT_PER_PIECE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#Weight_per_piece"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#x
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property X.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_X = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#x"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#y
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property Y.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_Y = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#y"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#z
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property Z.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_Z = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/ontologies/2017/1/WeighingModuleOntology1#z"));


}
